# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Auto Build CPD
tagline:          'Crealo tu mismo'
description:      'A reserved <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that places the utmost gravity on content with a hidden drawer. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:              http://elsudano.github.io/autobuildcpd/

author:
  name:           'Carlos de la Torre'
  url:            https://twitter.com/elsudano

paginate:         5

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/elsudano/autobuild
